# Generated by Django 4.0.3 on 2022-03-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Enter your Full name', max_length=100)),
                ('Username', models.CharField(help_text='Username', max_length=100)),
                ('Age', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('M', 'Man'), ('W', 'Woman')], default='M', max_length=10)),
                ('Sport', models.CharField(choices=[('GE ', 'GYM EXERCISES'), ('CR', 'CROSSFIT'), ('SW', 'SWIMMING'), ('FB', 'FOOTBALL'), ('HB', 'HANDBALL')], default='GE', max_length=10)),
                ('Weight', models.FloatField(help_text='Enter your weight in kgs', max_length=5)),
                ('Height', models.FloatField(help_text='Enter your height in Cm', max_length=5)),
                ('Hours', models.FloatField(help_text='Number of Hours at Work', max_length=5)),
                ('Effort', models.CharField(choices=[('LA ', 'Lightly Active'), ('MA', 'Moderately Active'), ('HA', 'Highly Active')], default='LA', help_text='YOUR EFFORT AT WORK ', max_length=10)),
                ('Goal', models.CharField(choices=[('L ', 'Lose Fat'), ('G', 'Gain Weight'), ('S', 'Stability on Weight')], default='LA', help_text='THE GOAL YOU WANT TO ACHIEVE', max_length=10)),
                ('Image', models.ImageField(null=True, upload_to='images')),
            ],
        ),
    ]
