# Generated by Django 4.0.3 on 2022-04-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0005_remove_person_password_alter_person_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Email',
        ),
        migrations.AlterField(
            model_name='person',
            name='Age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='Height',
            field=models.FloatField(help_text='Enter your height in Cm', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='Hours',
            field=models.FloatField(help_text='Number of Hours at Work', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='Weight',
            field=models.FloatField(help_text='Enter your weight in kgs', max_length=5, null=True),
        ),
    ]
