# Generated by Django 4.0.3 on 2022-04-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0006_remove_person_email_alter_person_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Height',
            field=models.FloatField(default=10, help_text='Enter your height in Cm', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='Weight',
            field=models.FloatField(default=10, help_text='Enter your weight in kgs', max_length=5),
            preserve_default=False,
        ),
    ]
