# Generated by Django 4.0.3 on 2022-04-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0007_alter_person_height_alter_person_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Height',
            field=models.FloatField(help_text='Enter your height in Cm', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='Weight',
            field=models.FloatField(help_text='Enter your weight in kgs', max_length=5, null=True),
        ),
    ]
