# Generated by Django 4.0.3 on 2022-04-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0008_alter_person_height_alter_person_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
