# Generated by Django 4.0.3 on 2022-04-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0009_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
