# Generated by Django 4.0.3 on 2022-05-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0011_person_inbody'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Sport',
            field=models.CharField(choices=[('GE ', 'GYM EXERCISES'), ('SP', 'SPRINTERS'), ('MMA', 'MMA'), ('FB', 'FOOTBALL'), ('BB', 'BASKETBALL')], default='GE', max_length=10),
        ),
    ]
