# Generated by Django 4.0.3 on 2022-06-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0013_alter_person_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(help_text='user_id', max_length=100)),
                ('add', models.CharField(help_text='add', max_length=100)),
                ('target', models.CharField(help_text='target', max_length=100)),
                ('duration', models.CharField(help_text='duration', max_length=100)),
            ],
        ),
    ]
