# Generated by Django 4.0.3 on 2022-06-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0014_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='add',
            name='add',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='add',
            name='duration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='add',
            name='target',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='add',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
    ]
